//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeopleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add.
        /// </summary>
        internal static string menu_add {
            get {
                return ResourceManager.GetString("menu_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Close.
        /// </summary>
        internal static string menu_close {
            get {
                return ResourceManager.GetString("menu_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Remove.
        /// </summary>
        internal static string menu_delete {
            get {
                return ResourceManager.GetString("menu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Edit.
        /// </summary>
        internal static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide age:.
        /// </summary>
        internal static string provideAge {
            get {
                return ResourceManager.GetString("provideAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide first and last name:.
        /// </summary>
        internal static string provideName {
            get {
                return ResourceManager.GetString("provideName", resourceCulture);
            }
        }
    }
}
